// data containing source nodes and a list of their target nodes
var nodes = [
	{name: "I"},
	{name: "II"},
	{name: "III"},
	{name: "IV"},
	{name: "V"},
	{name: "VI"},
	{name: "VII"}, // 7th movie, index 6
	{name: 'Ackbar', target: [5, 6]}, // 1st name, index 7
	//{name: 'Adi Gallia', target: [0, 2]},
	{name: 'Anakin Skywalker', target: [0, 1, 2]}, // 8
	//{name: 'Arvel Crynyd', target: [5]},
	{name: 'Ayla Secura', target: [0, 1, 2]},
	{name: 'Bail Prestor Organa', target:[1, 2]}, // 10
	//{name: 'Barriss Offee', target:[1]},
	{name: 'BB-8', target: [6]},
	//{name: 'Ben Quadinaros', target: [0]},
	{name: 'Beru Whitesun Lars', target: [1, 2, 3]},
	//{name: 'Bib Fortuna', target: [5]},
	//{name: 'Biggs Darklighter', target: [3]},
	{name: 'Boba Fett', target: [1, 4, 5]}, // 13
	//{name: 'Bossk', target: [4]},
	{name: 'C-3PO', target: [0, 1, 2, 3, 4, 5]},
	{name: 'Captain Phasma', target: [6]}, 
	{name: 'Chewbacca', target: [2, 3, 4, 5, 6]}, // 16
	//{name: 'Cliegg Lars', target: [1]},
	//{name: 'Corde', target: [1]},
	{name: 'Darth Maul', target: [0]}, // 17
	{name: 'Darth Vader', target: [2, 3, 4, 5]}, // 18
	//{name: 'Dexter Jettster', target: [1]},
	{name: 'Dooku', target: [1, 2]},
	//{name: 'Dorme', target: [1]},
	//{name: 'Dud Bolt', target: [0]},
	//{name: 'Eeth Koth', target: [0, 2]},
	//{name: 'Finis Valorum', target: [0]},
	{name: 'Finn', target: [6]}, // 20
	//{name: 'Gasgano', target: [0]},
	{name: 'Greedo', target: [3]}, 
	{name: 'Gregar Typho', target: [1]}, // 22
	{name: 'Grievous', target: [2]}, // 23
	{name: 'Han Solo', target: [3, 4, 5, 6]}, // 24
	//{name: 'IG-88', target: [4]},
	{name: 'Jabba Desilijic Tiure', target: [0, 3, 5]},
	{name: 'Jango Fett', target: [1]},
	{name: 'Jar Jar Binks', target: [0, 1]},
	//{name: 'Jocasta Nu', target: [1]},
	{name: 'Ki-Adi-Mundi', target: [0, 1, 2]},
	{name: 'Kit Fisto', target: [0, 1, 2]},
	//{name: 'Jek Tono Porkins', target: [3]},
	//{name: 'Lama Su', target: [1]},
	{name: 'Lando Calrissian', target: [4, 5]}, // 30
	{name: 'Leia Organa', target: [2, 3, 4, 5, 6]},
	//{name: 'Lobot', target: [4]},
	{name: 'Luke Skywalker', target: [2, 3, 4, 5, 6]}, // 32
	{name: 'Luminara Unduli', target: [1, 2]},
	{name: 'Mace Windu', target: [0, 1, 2]},
	//{name: 'Mas Amedda', target: [0, 1]},
	//{name: 'Mon Mothma', target: [5]}, 
	//{name: 'Nien Nunb', target: [5]}, 
	{name: 'Nute Gunray', target: [0, 1, 2]},
	{name: 'Obi-Wan Kenobi', target: [0, 1, 2, 3, 4, 5]}, // 36
	{name: 'Owen Lars', target: [1, 2, 3]},
	{name: 'Padme Amidala', target: [0, 1, 2]}, // 38
	{name: 'Palpatine', target: [0, 1, 2, 4, 5]},
	{name: 'Poe Dameron', target: [6]}, // 40
	{name: 'Plo Koon', target: [0, 1, 2]}, // 41
	//{name: 'Poggle the Lesser', target: [1, 2]},
	//{name: 'Quarsh Panaka', target: [0]},
	{name: 'Qui-Gon Jinn', target: [0]},
	{name: 'R2-D2', target: [0, 1, 2, 3, 4, 5, 6]},
	//{name: 'R4-P17', target: [1, 2]},
	//{name: 'R5-D4', target: [3]},
	//{name: 'Ratts Tyerell', target: [0]},
	{name: 'Raymus Antilles', target: [2, 3]},
	{name: 'Rey', target: [6]},
	//{name: 'Ric Olié', target: [0]},
	//{name: 'Roos Tarpals', target: [0]},
	//{name: 'Rugor Nass', target: [0]},
	//{name: 'Saesee Tiin', target: [0, 2]},
	//{name: 'San Hill', target: [1]},
	//{name: 'Sebulba', target: [0]},
	//{name: 'Shaak Ti', target: [1, 2]},
	{name: 'Shmi Skywalker', target: [0, 1]},
	//{name: 'Sly Moore', target: [1, 2]},
	//{name: 'Tarfful', target: [2]}, 
	//{name: 'Taun We', target: [1]},
	//{name: 'Tion Medon', target: [2]},
	//{name: 'Wat Tambor', target: [1]},
	//{name: 'Watto', target: [0, 1]},
	{name: 'Wedge Antilles', target: [3, 4, 5]}, // 47
	//{name: 'Wicket Systri Warrick', target: [5]},
	//{name: 'Wilhuff Tarkin', target: [2, 3]},
	//{name: 'Yarael Poof', target: [0]},
	{name: 'Yoda', target: [0, 1, 2, 4, 5]}, // 48
	//{name: 'Zam Wesell', target: [1]}
	
	//{name: 'A-wing', target: [5]},
	//{name: 'AA-9 Coruscant freighter', target: [1]},
	//{name: 'arc-170', target: [2]},
	//{name: 'B-wing', target: [5]},
	//{name: 'Banking clan frigate', target: [2]},
	{name: 'Belbullab-22 starfighter', target: [2, 23, 36]},
	//{name: 'Calamari Cruiser', target: [5]},
	{name: 'CR90 corvette', target: [2, 3, 5]},
	{name: 'Death Star', target: [3]},
	{name: 'Droid control ship', target: [0, 1, 2]},
	{name: 'Executor', target: [4, 5]},
	{name: 'EF76 Nebulon-B escort frigate', target: [4, 5]}, 
	{name: 'H-type Nubian yacht', target: [1, 38]},
	{name: 'Imperial shuttle', target: [4, 5, 16, 24, 32]},
	//{name: 'J-type diplomatic barge', target: [1]},
	{name: 'Jedi Interceptor', target: [2, 8, 36]},
	{name: 'Jedi starfighter', target: [1, 2, 36, 41]}, 
	{name: 'Millennium Falcon', target: [3, 4, 5, 6, 16, 24, 30]},
	// {name: 'Naboo Royal Starship', target: [0]},
	{name: 'Naboo fighter', target: [0, 1, 8, 22, 38]},
	{name: 'Naboo star skiff', target: [2, 36, 38]}, 
	{name: 'Rebel transport', 'target': [4, 5]},
	//{name: 'Republic Assault ship', target: [1]},
	//{name: 'Republic attack cruiser', target: [2]},
	//{name: 'Republic Cruiser', target: [0]},
	{name: 'Scimitar', target: [0, 17]},
	//{name: 'Sentinel-class landing craft', target: [3]},
	{name: 'Slave 1', target: [1, 4, 13]},
	//{name: 'Solar Sailer', target: [1]},
	{name: 'Star Destroyer', target: [3, 4, 5]},
	{name: 'T-70 X-wing fighter', target: [6, 40]},
	//{name: 'Theta-class T-2c shuttle', target: [2]},
	{name: 'TIE Advanced x1', target: [3, 18]}, 
	{name: 'Trade Federation cruiser', target: [2, 8, 36]},
	//{name: 'V-wing', target: [2]},
	{name: 'X-wing', target: [3, 4, 5]},
	{name: 'Y-wing', target: [4, 5, 32, 47]},
];